// Code generated by tools/generate.go - DO NOT EDIT
// Source: Connect-Auth/seeds/roles/community.json
// Generated: 2025-11-06 15:05:02

package roles

// COMMUNITY Scope Role Constants
const (
	COMMUNITY_STAFF = "community_staff" // Community Staff
	COMMUNITY_OWNER = "community_owner" // Community Owner
	COMMUNITY_USER = "community_user" // Community Member
)

// COMMUNITY Role Definitions
var (
	COMMUNITYCommunityStaff = Role{
		Scope:       "COMMUNITY",
		Name:        COMMUNITY_STAFF,
		Label:       "Community Staff",
		Description: "Community moderator with management capabilities",
		Groups:      []string{ "COMMUNITY__BASIC", "COMMUNITY__STAFF" },
	}
	COMMUNITYCommunityOwner = Role{
		Scope:       "COMMUNITY",
		Name:        COMMUNITY_OWNER,
		Label:       "Community Owner",
		Description: "Community owner with full administrative control",
		Groups:      []string{ "COMMUNITY__BASIC", "COMMUNITY__STAFF", "COMMUNITY__OWNER" },
	}
	COMMUNITYCommunityUser = Role{
		Scope:       "COMMUNITY",
		Name:        COMMUNITY_USER,
		Label:       "Community Member",
		Description: "Basic community member with participation rights",
		Groups:      []string{ "COMMUNITY__BASIC" },
	}
)

// GetCOMMUNITYRole returns a role definition by name
func GetCOMMUNITYRole(name string) (Role, bool) {
	switch name {
	case COMMUNITY_STAFF:
		return COMMUNITYCommunityStaff, true
	case COMMUNITY_OWNER:
		return COMMUNITYCommunityOwner, true
	case COMMUNITY_USER:
		return COMMUNITYCommunityUser, true
	default:
		return Role{}, false
	}
}

// GetCOMMUNITYRoles returns all COMMUNITY roles
func GetCOMMUNITYRoles() []Role {
	return []Role{
		COMMUNITYCommunityStaff,
		COMMUNITYCommunityOwner,
		COMMUNITYCommunityUser,
	}
}
