// Code generated by tools/generate.go - DO NOT EDIT

package roles

// Role defines a role with its associated permission groups
type Role struct {
	Scope       string
	Name        string
	Label       string
	Description string
	Groups      []string // Permission group keys
}

// HasRole checks if a role name exists in a list of roles
func HasRole(roleName string, userRoles []string) bool {
	for _, r := range userRoles {
		if r == roleName {
			return true
		}
	}
	return false
}

// GetRole returns a role definition by scope and name
func GetRole(scope, name string) (Role, bool) {
	switch scope {
	case "WEB":
		return GetWEBRole(name)
	case "TEAM":
		return GetTEAMRole(name)
	case "LOBBY":
		return GetLOBBYRole(name)
	case "COMMUNITY":
		return GetCOMMUNITYRole(name)
	default:
		return Role{}, false
	}
}

// GetAllRoles returns all roles for a scope
func GetAllRoles(scope string) []Role {
	switch scope {
	case "WEB":
		return GetWEBRoles()
	case "TEAM":
		return GetTEAMRoles()
	case "LOBBY":
		return GetLOBBYRoles()
	case "COMMUNITY":
		return GetCOMMUNITYRoles()
	default:
		return []Role{}
	}
}
