# Configuración de golangci-lint para Connect-Libraries
# https://golangci-lint.run/usage/configuration/

version: "2"

run:
  timeout: 5m

linters:
  default: none
  enable:
    # Recomendados por defecto
    - govet         # Examina código Go y reporta constructos sospechosos
    - ineffassign   # Detecta asignaciones ineficientes
    - staticcheck   # Análisis estático avanzado
    - unused        # Detecta código no usado
    
    # Adicionales para calidad de código
    - revive        # Linter rápido, reemplazo de golint
    - unconvert     # Detecta conversiones innecesarias
    
    # Estilo y buenas prácticas
    - gocyclo       # Detecta complejidad ciclomática alta
    - goconst       # Detecta strings que podrían ser constantes

  exclusions:
    rules:
      # Excluir ciertos linters en archivos de test
      - path: _test\.go
        linters:
          - gocyclo
          - goconst
          - revive

      # Permitir errores de shadowing en algunos casos
      - text: "shadow: declaration of"
        linters:
          - govet

  settings:
    govet:
      enable:
        - shadow
    
    gocyclo:
      min-complexity: 15
    
    goconst:
      min-len: 3
      min-occurrences: 3
    
    revive:
      confidence: 0.8
      rules:
        - name: package-comments
          disabled: true
    
formatters:
  enable:
    - gofmt         # Verifica formato del código
    - goimports     # Verifica imports

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
