// Code generated by tools/generate.go - DO NOT EDIT
// Source: Connect-Auth/seeds/roles/lobby.json
// Generated: 2025-11-06 15:05:02

package roles

// LOBBY Scope Role Constants
const (
	LOBBY_STAFF = "lobby_staff" // Lobby Staff
	LOBBY_OWNER = "lobby_owner" // Lobby Owner
	LOBBY_USER  = "lobby_user"  // Lobby User
)

// LOBBY Role Definitions
var (
	LOBBYLobbyStaff = Role{
		Scope:       "LOBBY",
		Name:        LOBBY_STAFF,
		Label:       "Lobby Staff",
		Description: "Lobby moderator with management capabilities",
		Groups:      []string{"LOBBY__BASIC", "LOBBY__STAFF"},
	}
	LOBBYLobbyOwner = Role{
		Scope:       "LOBBY",
		Name:        LOBBY_OWNER,
		Label:       "Lobby Owner",
		Description: "Lobby owner with full administrative control",
		Groups:      []string{"LOBBY__BASIC", "LOBBY__STAFF", "LOBBY__OWNER"},
	}
	LOBBYLobbyUser = Role{
		Scope:       "LOBBY",
		Name:        LOBBY_USER,
		Label:       "Lobby User",
		Description: "Basic lobby user with game participation rights",
		Groups:      []string{"LOBBY__BASIC"},
	}
)

// GetLOBBYRole returns a role definition by name
func GetLOBBYRole(name string) (Role, bool) {
	switch name {
	case LOBBY_STAFF:
		return LOBBYLobbyStaff, true
	case LOBBY_OWNER:
		return LOBBYLobbyOwner, true
	case LOBBY_USER:
		return LOBBYLobbyUser, true
	default:
		return Role{}, false
	}
}

// GetLOBBYRoles returns all LOBBY roles
func GetLOBBYRoles() []Role {
	return []Role{
		LOBBYLobbyStaff,
		LOBBYLobbyOwner,
		LOBBYLobbyUser,
	}
}
