// Code generated by tools/generate.go - DO NOT EDIT
// Source: Connect-Auth/seeds/roles/team.json
// Generated: 2025-11-06 15:05:02

package roles

// TEAM Scope Role Constants
const (
	TEAM_USER = "team_user" // Team Member
	TEAM_STAFF = "team_staff" // Team Staff
	TEAM_OWNER = "team_owner" // Team Owner
)

// TEAM Role Definitions
var (
	TEAMTeamUser = Role{
		Scope:       "TEAM",
		Name:        TEAM_USER,
		Label:       "Team Member",
		Description: "Basic team member with participation rights",
		Groups:      []string{ "TEAM__BASIC" },
	}
	TEAMTeamStaff = Role{
		Scope:       "TEAM",
		Name:        TEAM_STAFF,
		Label:       "Team Staff",
		Description: "Team moderator with management capabilities",
		Groups:      []string{ "TEAM__BASIC", "TEAM__STAFF" },
	}
	TEAMTeamOwner = Role{
		Scope:       "TEAM",
		Name:        TEAM_OWNER,
		Label:       "Team Owner",
		Description: "Team owner with full administrative control",
		Groups:      []string{ "TEAM__BASIC", "TEAM__STAFF", "TEAM__OWNER" },
	}
)

// GetTEAMRole returns a role definition by name
func GetTEAMRole(name string) (Role, bool) {
	switch name {
	case TEAM_USER:
		return TEAMTeamUser, true
	case TEAM_STAFF:
		return TEAMTeamStaff, true
	case TEAM_OWNER:
		return TEAMTeamOwner, true
	default:
		return Role{}, false
	}
}

// GetTEAMRoles returns all TEAM roles
func GetTEAMRoles() []Role {
	return []Role{
		TEAMTeamUser,
		TEAMTeamStaff,
		TEAMTeamOwner,
	}
}
