// Code generated by tools/generate.go - DO NOT EDIT
// Source: Connect-Auth/seeds/roles/web.json
// Generated: 2025-11-06 15:05:02

package roles

// WEB Scope Role Constants
const (
	WEB_USER  = "web_user"  // Web User
	WEB_STAFF = "web_staff" // Web Staff
	WEB_OWNER = "web_owner" // Web Owner
)

// WEB Role Definitions
var (
	WEBWebUser = Role{
		Scope:       "WEB",
		Name:        WEB_USER,
		Label:       "Web User",
		Description: "Basic web platform user with read access",
		Groups:      []string{"WEB__BASIC"},
	}
	WEBWebStaff = Role{
		Scope:       "WEB",
		Name:        WEB_STAFF,
		Label:       "Web Staff",
		Description: "Staff member with moderation capabilities",
		Groups:      []string{"WEB__BASIC", "WEB__STAFF"},
	}
	WEBWebOwner = Role{
		Scope:       "WEB",
		Name:        WEB_OWNER,
		Label:       "Web Owner",
		Description: "Platform owner with full administrative access",
		Groups:      []string{"WEB__BASIC", "WEB__STAFF", "WEB__OWNER"},
	}
)

// GetWEBRole returns a role definition by name
func GetWEBRole(name string) (Role, bool) {
	switch name {
	case WEB_USER:
		return WEBWebUser, true
	case WEB_STAFF:
		return WEBWebStaff, true
	case WEB_OWNER:
		return WEBWebOwner, true
	default:
		return Role{}, false
	}
}

// GetWEBRoles returns all WEB roles
func GetWEBRoles() []Role {
	return []Role{
		WEBWebUser,
		WEBWebStaff,
		WEBWebOwner,
	}
}
